name: Release h5
run-name: Release h5 ${{ github.ref_name }}

on:
  # Enable manual run
  workflow_dispatch:
    inputs:
      ref:
        type: string
        description: "The branch, tag or SHA to checkout. (default to main)"
        default: "main"
        required: false

# Declare default permissions as readonly.
permissions: read-all

env:
  repository: 'voicemeet/frontend-h5'
  main-path: 'main'
  source-path: 'h5'

jobs:
  h5:
    name: Create h5
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
        with:
          path: ${{ env.main-path }}

      - uses: actions/checkout@v5
        with:
          repository: ${{ env.repository }}
          ref: ${{ github.event.inputs.ref }}
          token: ${{ secrets.VM_RELEASE_TOKEN }}
          path: ${{ env.source-path }}

      - name: Set node
        uses: actions/setup-node@v5
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          package-manager-cache: false

      - name: Install deps
        run: |
          npm i -g corepack
          corepack enable
          pnpm install
        working-directory: ${{ env.source-path }}

      - name: Build
        run: pnpm build:pro
        working-directory: ${{ env.source-path }}

      - name: Copy files to dist
        run: cp LICENSE README.md ./dist
        working-directory: ${{ env.source-path }}

      - name: Copy index.html to 404.html
        run: cp ./dist/index.html ./dist/404.html
        working-directory: ${{ env.source-path }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          external_repository: voicemeet/h5.voicemeet.io
          publish_branch: main
          personal_token: ${{ secrets.VM_RELEASE_TOKEN }}
          publish_dir: ./${{ env.source-path }}/dist
          cname: h5.voicemeet.io
