name: Test website

on:
  repository_dispatch:
    types: [ website-push, website-pull_request ]

# Declare default permissions as readonly.
permissions: read-all

env:
  repository: 'voicemeet/frontend-website'
  main-path: 'main'
  source-path: 'website'

jobs:
  website:
    name: Create website
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
        with:
          path: ${{ env.main-path }}

      - uses: actions/checkout@v5
        with:
          repository: ${{ env.repository }}
          ref: ${{ github.event.client_payload.sha }}
          token: ${{ secrets.VM_RELEASE_TOKEN }}
          path: ${{ env.source-path }}

      - name: Set node
        uses: actions/setup-node@v5
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          package-manager-cache: false

      - name: Install deps
        run: |
          npm i -g corepack
          corepack enable
          pnpm install
        working-directory: ${{ env.source-path }}
