name: Test Windows store

on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        description: "The branch, tag or SHA to checkout. (default to main)"
        default: "main"
        required: false

# Declare default permissions as readonly.
permissions: read-all

env:
  repository: 'VoiceMeet/voicemeet'
  main-path: 'main'
  source-path: 'voicemeet'

jobs:
  get-version:
    name: Create release
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.version_step.outputs.version }}
      version_short: ${{ steps.version_step.outputs.version_short }}
      build_number: ${{ steps.version_step.outputs.build_number }}
    steps:
      - uses: actions/checkout@v5
        with:
          path: ${{ env.main-path }}

      - uses: actions/checkout@v5
        with:
          repository: ${{ env.repository }}
          ref: ${{ github.event.inputs.ref }}
          token: ${{ secrets.VM_RELEASE_TOKEN }}
          path: ${{ env.source-path }}

      - name: Set version
        id: version_step
        run: |
          VERSION=$(yq '.version' pubspec.yaml)
          echo "$VERSION"

          VERSION_SHORT=$(echo "$VERSION" | sed -e "s/+.*//")
          echo "VERSION_SHORT: $VERSION_SHORT."

          BUILD_NUMBER=$(echo "$VERSION" | sed -e "s/.*+//")
          echo "BUILD_NUMBER: $BUILD_NUMBER."

          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "version_short=$VERSION_SHORT" >> $GITHUB_OUTPUT
          echo "build_number=$BUILD_NUMBER" >> $GITHUB_OUTPUT
        working-directory: ${{ env.source-path }}

      - name: Check version
        run: echo ${{ steps.version_step.outputs.version }}

  windows-store:
    name: Create windows store
    runs-on: windows-2022
    env:
      Platform: x64
    needs:
      - get-version
    steps:
      - uses: actions/checkout@v5
        with:
          path: ${{ env.main-path }}

      - uses: actions/checkout@v5
        with:
          repository: ${{ env.repository }}
          ref: ${{ github.event.inputs.ref }}
          token: ${{ secrets.VM_RELEASE_TOKEN }}
          path: ${{ env.source-path }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.32.8'

      - name: Flutter doctor -v
        run: flutter doctor -v

      - name: Configure .env
        run: |
          echo "$pwd"
          $bytes = echo $env:ENV_KEY | %{[Convert]::FromBase64String($_)}
          [IO.File]::WriteAllBytes("$pwd\.env", $bytes)
        env:
          ENV_KEY: ${{ secrets.ENV_STG_BASE64_WINDOWS }}
        working-directory: ${{ env.source-path }}

      - name: copy eula.rtf to the windows folder
        run: Copy-Item -Path "$pwd\macos\packaging\base\eula.rtf" -Destination "$pwd\windows\LICENSE.rtf" -Force
        working-directory: ${{ env.source-path }}

      - name: Install yq
        shell: pwsh
        run: |
          choco install yq
          yq --version

      - name: Update config
        shell: pwsh
        run: |
          echo $env:RUNNER_TEMP
          # https://stackoverflow.com/questions/15414678/how-to-decode-a-base64-string
          # https://stackoverflow.com/questions/66239147/pfx-encoded-and-back-to-pfx-in-powershell
          $certificatePath = "$env:RUNNER_TEMP\voicemeet.pfx"
          $bytes = echo $env:WINDOWS_CERTIFICATE | %{[Convert]::FromBase64String($_)}
          [IO.File]::WriteAllBytes("$certificatePath", $bytes)

          $yamlFile = ".\pubspec.yaml"
          $yamlContent = Get-Content -Raw -Path $yamlFile

          # 获取环境变量的值
          # $identityName = (Get-Item -Path Env:WINDOWS_IDENTITY_NAME).Value
          # $publisher = (Get-Item -Path Env:WINDOWS_PUBLISHER).Value
          # $publisherName = (Get-Item -Path Env:WINDOWS_PUBLISHER_NAME).Value
          $certificatePassword = (Get-Item -Path Env:WINDOWS_CERTIFICATE_PASSWORD).Value

          # 使用 yq 更新多个字段
          $updatedYamlContent = echo $yamlContent | yq e ".msix_config.certificate_path = `"$certificatePath`" | .msix_config.certificate_password = `"$certificatePassword`" | del(.msix_config.identity_name) | del(.msix_config.publisher) | del(.msix_config.publisher_display_name)" -

          # 将更新后的内容写回文件
          Set-Content -Path $yamlFile -Value $updatedYamlContent
        env:
          WINDOWS_CERTIFICATE: ${{ secrets.WINDOWS_CERTIFICATE }}
          WINDOWS_CERTIFICATE_PASSWORD: ${{ secrets.WINDOWS_CERTIFICATE_PASSWORD }}
          WINDOWS_IDENTITY_NAME: ${{ secrets.WINDOWS_IDENTITY_NAME }}
          WINDOWS_PUBLISHER: ${{ secrets.WINDOWS_PUBLISHER }}
          WINDOWS_PUBLISHER_NAME: ${{ secrets.WINDOWS_PUBLISHER_NAME }}
        working-directory: ${{ env.source-path }}

      - name: Install flutter dependencies
        run: flutter pub get
        working-directory: ${{ env.source-path }}

      - name: Build windows
        run: |
          $env:SENTRY_NATIVE_BACKEND = "breakpad"
          flutter build windows --dart-define-from-file=.env
        working-directory: ${{ env.source-path }}

      - name: Crate msix
        run: |
          dart run msix:create --build-windows false --output-name "voicemeet-$env:VERSION_SHORT.$env:BUILD_NUMBER-windows-$env:Platform"
        env:
          VERSION_SHORT: ${{ needs.get-version.outputs.version_short }}
          BUILD_NUMBER: ${{ needs.get-version.outputs.build_number }}
        working-directory: ${{ env.source-path }}

      # Package the build.
      - name: Copy build for msix
        run: ls
        working-directory: ${{ env.source-path }}\build\windows\${{ env.Platform }}\runner\Release

      - uses: actions/upload-artifact@v4
        with:
          name: windows-msix-artifact
          path: .\${{ env.source-path }}\build\windows\${{ env.Platform }}\runner\Release\*.msix

      - name: Clean up
        if: ${{ always() }}
        run: |
          ls
          if (test-path -Path "$env:RUNNER_TEMP\voicemeet.pfx") {
            echo "$env:RUNNER_TEMP\voicemeet.pfx"
            remove-item -Path "$env:RUNNER_TEMP\voicemeet.pfx" -Force -ErrorAction SilentlyContinue
          } else {
            echo "File($env:RUNNER_TEMP\voicemeet.pfx) doesn't exist."
          }
          if (test-path -Path "$pwd\.env") {
            echo "Remove file($pwd\.env)"
            remove-item -Path "$pwd\.env" -Force -ErrorAction SilentlyContinue
          } else {
            echo "File($pwd\.env) doesn't exist."
          }
        working-directory: ${{ env.source-path }}
